apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-demo

resources:
  - ../../base

labels:
  - pairs:
      site: christchurch-addington

patches:
  - target:
      kind: Deployment
      name: iccp-simulator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: iccp-simulator-christchurch-addington
        labels:
          site: christchurch-addington
      spec:
        selector:
          matchLabels:
            site: christchurch-addington
        template:
          metadata:
            labels:
              site: christchurch-addington
          spec:
            containers:
            - name: iccp-simulator
              env:
              - name: SITE_NAME
                value: "christchurch-addington"
              - name: ELASTIC_APM_SERVICE_NAME
                value: "iccp-simulator-christchurch-addington"
