apiVersion: apps/v1
kind: Deployment
metadata:
  name: iccp-simulator-auckland-penrose
spec:
  template:
    spec:
      containers:
      - name: simulator
        image: banjodocker/iccp-simulator:latest
