apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-demo

resources:
  - ../../base

labels:
  - pairs:
      site: wellington-central

patches:
  - target:
      kind: Deployment
      name: iccp-simulator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: iccp-simulator-wellington-central
        labels:
          site: wellington-central
      spec:
        selector:
          matchLabels:
            site: wellington-central
        template:
          metadata:
            labels:
              site: wellington-central
          spec:
            containers:
            - name: iccp-simulator
              env:
              - name: SITE_NAME
                value: "wellington-central"
              - name: ELASTIC_APM_SERVICE_NAME
                value: "iccp-simulator-wellington-central"
