apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transpower-demo

resources:
  - configmap.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: iccp-simulator
  app.kubernetes.io/component: simulator
