apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-demo

resources:
  - ../../base

nameSuffix: -wellington-central

labels:
  - pairs:
      site: wellington-central

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: wellington-central
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ELASTIC_APM_SERVICE_NAME
          value: iccp-simulator-wellington-central
    target:
      kind: Deployment
      name: iccp-simulator
