apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-demo

resources:
  - ../../base

labels:
  - pairs:
      site: huntly-power

patches:
  - target:
      kind: Deployment
      name: iccp-simulator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: iccp-simulator-huntly-power
        labels:
          site: huntly-power
      spec:
        selector:
          matchLabels:
            site: huntly-power
        template:
          metadata:
            labels:
              site: huntly-power
          spec:
            containers:
            - name: iccp-simulator
              env:
              - name: SITE_NAME
                value: "huntly-power"
              - name: ELASTIC_APM_SERVICE_NAME
                value: "iccp-simulator-huntly-power"
