apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-demo

nameSuffix: -auckland-penrose

resources:
  - ../../base

labels:
  - pairs:
      site: auckland-penrose

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: iccp-simulator-auckland-penrose
        labels:
          site: auckland-penrose
      spec:
        selector:
          matchLabels:
            site: auckland-penrose
        template:
          metadata:
            labels:
              site: auckland-penrose
          spec:
            containers:
            - name: iccp-simulator
              env:
              - name: SITE_NAME
                value: "auckland-penrose"
              - name: ELASTIC_APM_SERVICE_NAME
                value: "iccp-simulator-auckland-penrose"
